### ISSUE TITLE
PGN 130052 - 130053 - 130054

### ISSUE THREAD

**Issue by arthurguyader** [canboat/canboat#125]
Good morning,

Firstly, thank you for your work.

I found on a documentation of NMEA2000, the pgn : 
- 130052 : Loran-C TD Data
- 130053 : Loran-C Range Data
- 130054 : Loran-C Signal Data
But they are not processed by the analyzer.

Is there a particular reason?

**Comment by sbender9** [comment]
Most likely it's because no one has needed them. Loran-C signals were shut down in the US in 2010.

PR's with example data are welcome!

**Comment by arks-public** [comment]
I added these PGNs to pgn.h and the analyzer seems to be working correctly, but I'm not sure what else needs to be updated, is it just the XML? And also, I'm not sure what units (if any) are needed on the Range fields.

https://github.com/canboat/canboat/commit/0c4cc782afaf3c37b5f50c3e2953f38b351e8d07

**Comment by keesverruijt** [comment]
For best results, if you are preparing a PR:

1. run `make generated` from the project root directory. If this fails because of missing tools, see `BUILDING.md`.
2. Verify your changes. If you changed the layout of the XML files, bump the major version number in `common/version.h`. If you change the type or name of one or more existing fields in a PGN, bump the middle number in `common/version.h`. If you add something 
3. Document your changes in CHANGELOG.md.
4. re-run `make generated`.
5. verify changes again.
6. commit + push.

**Comment by keesverruijt** [comment]
Make sure you tag the missing attributes properly if you are unsure of stuff!

Something like

    .complete = PACKET_FIELDS_UNKNOWN | PACKET_RESOLUTION_UNKNOWN

**Comment by arks-public** [comment]
Thanks for the detailed advice, it definitely helped to make a successful PR.

I think this issue can be closed now that PGNs 130052, 130053, and 130054 were added in v4.8.0.
