### ISSUE TITLE
Advise to range check Rate of Turn in PGN 129038 

### ISSUE THREAD

**Issue by larsujensen** [canboat/canboat#162]
Rate of turn in an ais "Class A Position Report" is an 8 bit signed integer with special meaning of the values +- 127. As canboat does not detect these special values, an advise is to range check that the magnitude of rate of turn from PGN 129038 is below say 0,208 rad/s.

**Comment by keesverruijt** [comment]
Ha, this is such a beautiful example of how not just me, or open source people, but entire companies get their stuff wrong.

You're right, Rate of Turn in the over-the-air messages is a 8 bit signed integer indicating deg/s, but in NMEA2000 it is a 16 bit integer expressed in rad/s. 
It is on the AIS-to-NMEA2000 device to translate -127 (0x80) to 0xffff (the special value in N2K to indicate a 16 bit value is "missing".)

Since chartplotters don't do this either, I don't think CANboat should hide these values.

Side note: for years my Navico AIS 300 did this wrong as well. All sorts of boats without heading (which is a special class of vessel, uncommon on the seas but common on Dutch inland waters) would be shown on my chartplotter as all having the same heading. When I reported this to Navico they sent me a free NAIS-400 to test to see if it was fixed!
