### ISSUE TITLE
Two ways of writing "AIS RAIM flag"

### ISSUE THREAD

**Issue by meaning-matters** [canboat/canboat#293]
The JSON contains both `"AIS RAIM flag"` and `"AIS RAIM Flag"`.  Should use only one spelling.

**Comment by keesverruijt** [comment]
Please verify as fixed on master.

**Comment by arks-public** [comment]
It looks like the goal was to change all occurrences of "RAIM", "AIS RAIM Flag", and "AIS RAIM flag" to just be "RAIM"?

I can verify this was accomplished in all the main files. However, I did find three occurrences of "AIS RAIM flag" in n2kd/gps_ais.c

I don't know if this file was supposed to be updated as part of the change. If not, then this issue is fixed on master.

**Comment by meaning-matters** [comment]
Just checked the JSON and it's nicely `RAIM` in every occurrence of this field.

**Comment by keesverruijt** [comment]
The AIS flags in gps_ais.c are fixed in #318
