### ISSUE TITLE
Invalid pngs.json

### ISSUE THREAD

**Issue by jeronimo** [canboat/canboat#56]
Not sure how this is generated but in **pngs.json** file for **127489** png for `discreteStatus1` and `discreteStatus2` fields **EnumBitValues** is invalid JSON (from https://en.wikipedia.org/wiki/JSON - Object: an unordered collection of name/value pairs where the names (also called keys) are strings) and can't be parsed by other parsers.
Instead of `{Bit:'0',Name:'Check Engine'}` shoud be `{'Bit':'0','Name':'Check Engine'}`

If there won't be any more xml changes I can just update that json file manually and make pull request myself.

**Comment by tkurki** [comment]
See https://github.com/canboat/canboat/blob/master/analyzer/Makefile#L34.

It used to work. Imho it would be a better idea to fix the generation, not the result. 

An optional json validation step would not hurt, maybe with vanilla ruby or python so that you would not need to install extra tools for that.

**Comment by canboat** [comment]
'them bitvalues, they be new yah!
